Add option to suppress warning about the Microsoft C/C++ extension incompatibility
clangd/vscode-clangd pull request #221
Opened 2021-08-16 16:22 UTC by matms

I've added an option to control suppression of the incompatibility warning (and not change the C/C++ settings).

I'm making this pull request as suggested in https://github.com/clangd/vscode-clangd/issues/162, since others seem to have faced this same issue.

2021-08-19 06:48 UTC, kirillbobyrev requested changes
Hey, sorry, I originally missed the patch. Thanks for picking it up and working on this! The logic looks good, I have a couple of suggestions that would make this patch even more awesome, would be happy to accept once resolved!

2021-08-19 06:48 UTC, kirillbobyrev commented on package.json
> +                "clangd.detectAndDisableExtensionConflicts": {
nit: how about `clangd.detectExtensionConflicts` + `Warn about conflicting extensions and suggest disabling them.`?

2021-08-19 06:48 UTC, kirillbobyrev commented on src/extension.ts
> +                  'Disable IntelliSense')
Nit: I think the perfect UX/UI would be adding a button `Don't show this warning`.

Something like 

```typescript
vscode.window.showWarningMessage('', ['Disable IntelliSense', 'Don\'t show this warning']).
    then(selection => {
        if (selection = 'Don\'t show this warning') {
            /* update clangd.detectAndDisableExtensionConflicts similar to what we
               have with C_Cpp.intelliSenseEngine right now */
        }
    }
```

2021-08-19 06:49 UTC, kirillbobyrev commented
(also, please `clang-format` the code before submitting, otherwise the CI linters will complain)

2021-08-20 16:41 UTC, matms commented
Done. This patch also means you don't have to restart VsCode, since it should now clear the interval upon pressing 'Never show this message'.

Note that if this option is later used for _other_ incompatibilities, then pressing 'Never show this message' would disable all of them.

2021-08-24 12:31 UTC, kirillbobyrev commented
Tested, works great, thank you for working on this!

2021-08-24 12:31 UTC, merged