Add handling of predefined variable ${workspaceFolderBasename}
clangd/vscode-clangd pull request #642
Opened 2024-06-20 12:02 UTC by yerseg

It's useful in my scenario when I'm creating a build dir that name depends on the name of workspace

2024-06-21 07:22 UTC, HighCommander4 approved these changes
Thank you for fixing!

2024-06-21 07:24 UTC, HighCommander4 requested changes
Looks like there's a clang-format failure (I think just trailing whitespace after the `&&`), could you fix it please?

2024-06-21 10:42 UTC, yerseg commented
@HighCommander4 fixed it, thank you

2024-06-23 00:06 UTC, HighCommander4 approved these changes

2024-06-23 00:06 UTC, merged